### ISSUE TITLE
grow_disks is stuck to zpool online rpool -e /dev/sda4

### ISSUE THREAD

**Issue by KajWiik** [psy0rz/alpinebox#11]
I have run the installer in several Proliant servers (two disks with mirror) without any problems.

Now I tried it in an old laptop (EEE PC 1005) with an upgraded HD (256 GB SSD) and it gets stuck in `zpool online rpool -e /dev/sda4`. No error messages, nothing related in dmesg. If I start another tty and try to log in, it is stuck too.

Maybe this is a zfs bug but I ask in case someone has solved this already.

**Comment by psy0rz** [comment]
Which version of Alpinebox?

Did you install Alpinebox on that disk before?

Its important to reguid the zpool if you used the imaging method to install it. Otherwise zfs will get confused by the same guid of the previous install, and hang or crash.

**Comment by KajWiik** [comment]
Version is the latest stable. 

Yes, there was an install, good point. 

But I think I know the most probable cause: RAM (DOH!). Trying to run ZFS with only 1 GB RAM is looking for a trouble. Unfortunately I did not think of this at all, sorry. I think you can close this issue.

**Comment by psy0rz** [comment]
Thats possible, no problem :)

For other people: i've had this issue before, so when zfs hangs, without IO and messages in the dmesg, its probably a GUID issue.
