### ISSUE TITLE
What is this ? 

### ISSUE THREAD

**Issue by Denyreal** [psy0rz/alpinebox#2]
hey thanks for your terrific installer.

Just curious what the hell is this ? 

https://github.com/psy0rz/alpinebox/blob/master/add-datux-keys

**Comment by psy0rz** [comment]
Dont worry, it never is automaticly executed (and never will). We execute it manually on servers we install ourselfs. 

Its also mentioned in the readme.

If people really dont like it we can remove it, but it does nothing.

**Comment by Denyreal** [comment]
it's definitely a very bad idea to leave this in your code. 

1. for people to trust you never ever try to copy some pubkeys in .ssh/authorized_keys
2. for the sake of good practices never ever put secrets even pukeys in git
3. why writing a script that does nothing ?

**Comment by psy0rz** [comment]
I only agree with point 1, ill remove it.

As for point 3: we do use it ourselfs to have to do less typing when adding our keys. (When there is only vps console access without a copy/paste possibilty)

**Comment by Denyreal** [comment]
I must insist and i am the obnoxious person highly recommending you to use .gitignore or to vault sensitive stuff in your code .

It's a red flag to publish code with scripts copying such sensitive stuff as actual pubkeys to such sensitive place at .ssh/authorized_keys whatsoever your needs.
