### ISSUE TITLE
-==Request==-- Need Wi-Fi out of the box...

### ISSUE THREAD

**Issue by megvadulthangya** [psy0rz/alpinebox#5]
Hello Edwin!

I installed Alpinebox on my Asus x101 which has only Wi-Fi but im stuck after installation without anything... Im just here to ask if you can add to the image the wireless-tools and wpa_supplicant packages.

BTW Thank you for this easy to install Alpine thingy, that saved me lot of time, to learn how to do it, from tutorials etc...

_"Now i go back and figure out how to add those 2 packages... maybe dload to pendrive and install manually :) "_

Don't forget to have yourself a good day.

**Comment by jTd7bPLFb** [comment]
Save yourself time and get a usb to rj45 adapter.
They are like $10 on amazon, and have linux support mostly out of the box.

**Comment by psy0rz** [comment]
while @jTd7bPLFb has a point, i'll still add these packages. I think its important that network support is as complete as possible

**Comment by psy0rz** [comment]
Coud you try v3.20-3 ?

**Comment by psy0rz** [comment]
like this:
```
# sh image /dev/sda v3.20-3

```

**Comment by megvadulthangya** [comment]
> like this:
> 
> ```
> # sh image /dev/sda v3.20-3
> ```

Thank you for listening to me. I will give a try tomorrow, after my morning coffe. I have another conifg which has wifi on it...  i will install like you suggest.  Then give you a feedback here.

Thank you for your time.


BTW I dloaded the whole main mirror to my external usb hard drive, then add mount point to /etc/apk/repositories .... This way installed...

_Couse installing in wmvare, then restore from the vmdk disk file with rescuezilla takes lot of time ... plus creating some weird issues with zsf after restoring--->then alpinebox grow-disks  script freezes, the whole sys then bootloop Not even worth to mention..._

**Comment by megvadulthangya** [comment]
Thank you man! Its working like it should.

**Comment by psy0rz** [comment]
awesome! Alpine is the best :)
