### ISSUE TITLE
3.20.2 default VIM ... i cant change it

### ISSUE THREAD

**Issue by megvadulthangya** [psy0rz/alpinebox#6]
Looks like in this version the default editor is vim, and i cant change it... for the root account....

.bashrc 
or
.profile
i put both

export EDITOR=/usr/bin/nano but nothing has changed after reboot.

only works when

source ~/.bashrc

**Comment by megvadulthangya** [comment]
only this works: 

rm /usr/bin/vi

ln -s /usr/bin/nano /usr/bin/vi

**Comment by psy0rz** [comment]
I think this is more of an Alpine / Linux issue?

**Comment by megvadulthangya** [comment]
> I think this is more of an Alpine / Linux issue?

Yes! Definetly is...
