### ISSUE TITLE
Question !? Apparmor does not seems to work. 

### ISSUE THREAD

**Issue by megvadulthangya** [psy0rz/alpinebox#8]
I manage to replace my os on my headless home server to alpinebox from debian... 
using your script everithing smooth... using much less space, wordpress docker much smoother in this os im happy:)

But...

 this is 2 much for me :'( im just a noob 

I do everything what is in [Trafotin's video](https://youtu.be/YNYtJ3jyMRs?t=1637), plus i opened alpine wiki apparmor as well...

Maybe try to use the edge main repo to install newest apparmor? then swithc back to 3.20 ?
What to do where to ask?

Help me please, if you can.

[root@gshoots ~]$ doas aa-status
apparmor module is loaded.
apparmor filesystem is not mounted.

I googled the apparmor module is loaded.
apparmor filesystem is not mounted. On alpine linux but i dont find helpfull content. :'(

[root@gshoots ~]# apparmor_parser -r /etc/apparmor.d/*
Cache read/write disabled: interface file missing. (Kernel needs AppArmor 2.4 co                                                                                             mpatibility patch.)
Warning: unable to find a suitable fs in /proc/mounts, is it mounted?
Use --subdomainfs to override.

[root@gshoots ~]# cat /boot/config-$(uname -r) | grep CONFIG_SECURITY_APPARMOR
CONFIG_SECURITY_APPARMOR=y
# CONFIG_SECURITY_APPARMOR_DEBUG is not set
CONFIG_SECURITY_APPARMOR_INTROSPECT_POLICY=y
CONFIG_SECURITY_APPARMOR_HASH=y
CONFIG_SECURITY_APPARMOR_HASH_DEFAULT=y
CONFIG_SECURITY_APPARMOR_EXPORT_BINARY=y
CONFIG_SECURITY_APPARMOR_PARANOID_LOAD=y

[root@gshoots ~]# sudo mount -t securityfs securityfs /sys/kernel/security
[root@gshoots ~]# apparmor_parser -r /etc/apparmor.d/*
Cache read/write disabled: interface file missing. (Kernel needs AppArmor 2.4 co                                                                                             mpatibility patch.)
Warning: unable to find a suitable fs in /proc/mounts, is it mounted?
Use --subdomainfs to override.

[root@gshoots ~]# sudo mount -t securityfs securityfs /sys/kernel/security
[root@gshoots ~]# grep 'securityfs' /proc/mounts
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
securityfs /sys/kernel/security securityfs rw,relatime 0 0
securityfs /sys/kernel/security securityfs rw,relatime 0 0

[root@gshoots ~]# sudo /etc/init.d/apparmor restart
 * WARNING: you are stopping a boot service
 * Stopping AppArmor ...
 *   Unloading AppArmor profiles
 *   Root privileges not available                                        [ !! ]
 * Starting AppArmor ...
 *   Loading AppArmor profiles ...
Cache read/write disabled: interface file missing. (Kernel needs AppArmor 2.4 co                                                                                             mpatibility patch.)
Warning: unable to find a suitable fs in /proc/mounts, is it mounted?
Use --subdomainfs to override.
 *   At least one profile failed to load                                  [ !! ]

[root@gshoots ~]# sudo mount -o remount,rw,relatime securityfs /sys/kernel/secur
ity
[root@gshoots ~]# /etc/init.d/apparmor restart
 * WARNING: you are stopping a boot service
 * Stopping AppArmor ...
 *   Unloading AppArmor profiles
 *   Root privileges not available                                        [ !! ]
 * Starting AppArmor ...
 *   Loading AppArmor profiles ...
Cache read/write disabled: interface file missing. (Kernel needs AppArmor 2.4 co                                                                                             mpatibility patch.)
Warning: unable to find a suitable fs in /proc/mounts, is it mounted?
Use --subdomainfs to override.
 *   At least one profile failed to load                            

This is what i do... i dont uderstand half of it... O.o

[Where to next](https://tenor.com/en-GB/view/pulpfiction-john-travolta-lost-gif-12409710)?

**Comment by psy0rz** [comment]
Sorry, Alpinebox is the installer for Alpine Linux. So I can only answer questions related to this installer and ZFS.

**Comment by megvadulthangya** [comment]
I just leave this here... 

This problem is related to using the zfsbootmenu... 

 i don't find where the hack can i set what i manage to set in [syslinux or grub](https://wiki.alpinelinux.org/wiki/AppArmor) 
 (?Load Kernel module?)
 
 But this don't matter now, to me...
 
 _I just switched to regular alpine with btrfs Reason i give up this thing... 
Couse its a pain in butt to create backup for the system because rescuzilla lack of zfs (module in kernel... as i remember) support,
And this way rescuezilla save zfs partition sector by sector that needed more then 3 hours to create image and created a 40GB image from the system which is only 20 GB or smthing.._

 Thank you for your time
